version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: testdb_container
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    ports:
      - "5433:5432"
    restart: always