name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose netcat

      - name: Build and run containers
        run: docker-compose -f docker/docker-compose.yml up --build -d

      - name: Wait for Postgres on port 5433
        run: |
          echo "Waiting for Postgres to be ready on port 5433..."
          for i in {1..20}; do
            if nc -z localhost 5433; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Postgres not ready yet, sleeping 2s..."
            sleep 2
          done
          echo "Postgres never became ready, failing."
          exit 1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest